/**
 * route-capabilities — ทะเบียนกลาง "route/หน้าของร้านไหน ต้องมี capability อะไร" (00071 P3 · S-12 · BR-RP-11)
 *
 * ทำไมเป็นทะเบียนกลาง ไม่ export จากไฟล์ route: Next 16 ไม่ยอมให้ `route.ts` export อะไรนอกจาก handler (F-7)
 * ตัวบังคับจริงคือ `__tests__/route-capability-inventory.test.ts` — สแกนซอร์สจริง:
 *   1) ทุกไฟล์ที่ resolve ร้านต้องมีรายการที่นี่ (ลืมประกาศ = เทสแดง)  2) key ต้องมีไฟล์จริง
 *   3) status 'DECLARED' = method body เรียกด่านด้วย literal cap ตรงทะเบียน  4) คลาสที่ไม่ใช่ cap ห้ามเรียกตัวหาร้านดิบ
 *
 * status: 'PENDING' = จัดหมวดแล้วแต่โค้ดยังใช้ด่านเดิม (ยังไม่ migrate) · T2/T3/T4 พลิกเป็น 'DECLARED' ตอนย้ายเข้า shop-capability
 *   ปิดงาน (T10): ต้องไม่เหลือ PENDING
 * cap เป็นอาร์เรย์ = ต้องผ่านทุกตัว (AND) เช่น housekeeping ต้อง Q1 และ O4
 * เซลล์มีเงื่อนไขต่อใบ (O3/O5 ของ BILLING · P1 ของ BILLING) ใส่ cap ฐานไว้ที่นี่ — เงื่อนไขต่อใบบังคับใน service (D-6)
 */
import type { Capability } from '@/lib/shop-permissions'

export type RouteClass = 'MEMBER' | 'SELF' | 'BUYER' | 'PUBLIC' | 'PLATFORM_ADMIN' | 'CRON' | 'WEBHOOK'
export type Caps = Capability | readonly Capability[]
export type RouteStatus = 'DECLARED' | 'PENDING'
export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'

export type CapEntry = { [M in HttpMethod]?: Caps } & { page?: Caps; status: RouteStatus }
export type ClassEntry = { class: RouteClass; reason: string; status: RouteStatus }
export type RouteEntry = CapEntry | ClassEntry

export function isClassEntry(e: RouteEntry): e is ClassEntry {
  return 'class' in e
}

/**
 * คลาสตามคำนำหน้า path — ส่วนที่ไม่ใช่ "สมาชิกร้านใช้ร้านที่ active" ทั้งโฟลเดอร์
 * MEMBER = สมาชิกทุกบทบาทเข้าได้โดยตั้งใจ (ไม่ใช่ capability) · SELF = ข้อมูลของผู้ใช้เอง/ร้านส่วนตัวของตัวเอง
 */
export const PREFIX_CLASSES: readonly { prefix: string; class: RouteClass; reason: string }[] = [
  { prefix: 'src/app/api/admin/', class: 'PLATFORM_ADMIN', reason: 'แอดมินแพลตฟอร์ม — ตรวจ admin session ไม่ใช่สมาชิกร้าน' },
  { prefix: 'src/app/(paces)/admin/', class: 'PLATFORM_ADMIN', reason: 'แอดมินแพลตฟอร์ม — ตรวจ admin session ไม่ใช่สมาชิกร้าน' },
  { prefix: 'src/app/api/app/', class: 'BUYER', reason: 'แอปมือถือผู้ซื้อ (Bearer token) — ไม่มีบทบาทร้าน' },
  { prefix: 'src/app/api/cron/', class: 'CRON', reason: 'เรียกด้วย CRON_SECRET ไม่มีผู้ใช้/บทบาท' },
  { prefix: 'src/app/api/webhooks/', class: 'WEBHOOK', reason: 'webhook ภายนอก — ตรวจลายเซ็น/secret ของผู้ให้บริการ' },
  { prefix: 'src/app/api/channels/facebook/webhook/', class: 'WEBHOOK', reason: 'webhook Meta — ตรวจลายเซ็น' },
  { prefix: 'src/app/api/channels/line/webhook/', class: 'WEBHOOK', reason: 'webhook LINE — ตรวจลายเซ็น' },
  { prefix: 'src/app/api/line-report/webhook/', class: 'WEBHOOK', reason: 'webhook LINE OA กลาง (รายงานกลุ่ม) — ตรวจลายเซ็น' },
]

/** รายการของ path นี้: exact ก่อน แล้วคำนำหน้า (prefix = DECLARED เสมอ) */
export function lookupRouteEntry(path: string): RouteEntry | undefined {
  const exact = ROUTE_CAPABILITIES[path]
  if (exact) return exact
  const p = PREFIX_CLASSES.find((c) => path.startsWith(c.prefix))
  return p ? { class: p.class, reason: p.reason, status: 'DECLARED' } : undefined
}

export const ROUTE_CAPABILITIES: Record<string, RouteEntry> = {
  'src/app/(paces)/seller/(chat)/inbox/[conversationId]/page.tsx': { page: 'H1', status: 'PENDING' },
  'src/app/(paces)/seller/(chat)/inbox/comments/page.tsx': { page: 'H1', status: 'PENDING' },
  'src/app/(paces)/seller/(chat)/inbox/page.tsx': { page: 'H1', status: 'PENDING' },
  'src/app/(paces)/seller/(chat)/layout.tsx': { page: 'H1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/account/page.tsx': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/admins/page.tsx': { page: 'T2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/auctions/[id]/page.tsx': { page: 'X1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/auctions/page.tsx': { page: 'X1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/badges/page.tsx': { class: 'MEMBER', reason: 'หน้ารวมของสมาชิกทุกคน — ความสำเร็จ/แจ้งเตือน/หน้าแรก/หน้าร้าน (C-1/C-8) · ตัวเลขเงินตัดตามระดับเงินใน service ไม่ใช่ด่านหน้า', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/bookings/[token]/page.tsx': { page: 'O1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/bookings/new/page.tsx': { page: 'O2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/bookings/page.tsx': { page: 'O1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/[shopId]/invites/page.tsx': { page: 'T2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/[shopId]/onboarding/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/create/page.tsx': { class: 'SELF', reason: 'สร้างร้านธุรกิจใหม่ของผู้ใช้เอง — โควตาแพ็กเกจตัดสินใน service', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/business/line-reports/[groupId]/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/line-reports/new/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/line-reports/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/page.tsx': { class: 'SELF', reason: 'แพ็กเกจ/ร้านธุรกิจของผู้ใช้เอง — อ่านร้านส่วนตัว (getPersonalShop) ไม่ผูกร้านที่ active · PENDING: ยังเรียก resolveReportAccess ตัดสินลิงก์รายงาน LINE — T6 ย้ายเป็น canSeePage', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/business/subscribe/page.tsx': { class: 'SELF', reason: 'สมัครแพ็กเกจธุรกิจของผู้ใช้เอง — ยังไม่มีร้านธุรกิจให้ผูกบทบาท', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/calendar/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/categories/page.tsx': { page: 'P2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/customers/[id]/page.tsx': { page: 'C1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/customers/page.tsx': { page: 'C1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/dashboard/page.tsx': { class: 'MEMBER', reason: 'หน้ารวมของสมาชิกทุกคน — ความสำเร็จ/แจ้งเตือน/หน้าแรก/หน้าร้าน (C-1/C-8) · ตัวเลขเงินตัดตามระดับเงินใน service ไม่ใช่ด่านหน้า', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/expenses/page.tsx': { page: 'F1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/follow-ups/page.tsx': { page: 'X2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/housekeepers/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/inspection/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/inventory/movements/[productId]/page.tsx': { page: 'P2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/inventory/page.tsx': { page: 'P2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/layout.tsx': { class: 'MEMBER', reason: 'shell ของ dashboard — resolve ร้านเพื่อโหลดเมนู/provider ไม่ตัดสินสิทธิ์ (หน้าลูกแต่ละหน้าประกาศ cap เอง · เมนูกรองใน T6)', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/notifications/page.tsx': { class: 'MEMBER', reason: 'หน้ารวมของสมาชิกทุกคน — ความสำเร็จ/แจ้งเตือน/หน้าแรก/หน้าร้าน (C-1/C-8) · ตัวเลขเงินตัดตามระดับเงินใน service ไม่ใช่ด่านหน้า', status: 'DECLARED' },
  'src/app/(paces)/seller/(dashboard)/orders/[token]/page.tsx': { page: 'O1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/orders/page.tsx': { page: 'O1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/products/[id]/page.tsx': { page: 'P1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/products/page.tsx': { page: 'P1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/public-profile/page.tsx': { page: 'T1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/queues/[resourceId]/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/queues/new/page.tsx': { page: 'Q2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/queues/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/reports/agents/[agentId]/page.tsx': { page: 'X4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/reports/agents/page.tsx': { page: 'X4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/reports/products/page.tsx': { page: 'F1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/reviews/page.tsx': { page: 'T1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/rooms/[roomId]/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/rooms/new/page.tsx': { page: 'Q2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/rooms/page.tsx': { page: 'Q1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/sales/page.tsx': { page: 'F1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/ai/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/auto-reply/[id]/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/auto-reply/new/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/auto-reply/order-agent/page.tsx': { page: 'X3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/auto-reply/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/channels/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/channels/select/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/chatbot/knowledge/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/chatbot/logs/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/chatbot/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/comment-reply/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/job-types/[resourceId]/page.tsx': { page: 'Q2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/job-types/new/page.tsx': { page: 'Q2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/job-types/page.tsx': { page: 'Q2', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/settings/page.tsx': { page: 'T3', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/shop/page.tsx': { class: 'MEMBER', reason: 'หน้ารวมของสมาชิกทุกคน — ความสำเร็จ/แจ้งเตือน/หน้าแรก/หน้าร้าน (C-1/C-8) · ตัวเลขเงินตัดตามระดับเงินใน service ไม่ใช่ด่านหน้า · PENDING: ยังเรียก resolveReportAccess ตัดสินลิงก์รายงาน LINE — T6 ย้ายเป็น canSeePage', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/subscriptions/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/verification/page.tsx': { page: 'T1', status: 'PENDING' },
  'src/app/(paces)/seller/(dashboard)/wallet/page.tsx': { page: 'F3', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/auctions/[id]/edit/page.tsx': { page: 'X1', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/auctions/new/page.tsx': { page: 'X1', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/business/line-reports/[groupId]/template/page.tsx': { page: 'T4', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/layout.tsx': { class: 'MEMBER', reason: 'shell ของจอเต็ม — resolve ร้านเพื่อโหลด provider ไม่ตัดสินสิทธิ์ (หน้าลูกประกาศ cap เอง)', status: 'DECLARED' },
  'src/app/(paces)/seller/(fullscreen)/orders/[token]/edit/page.tsx': { page: 'O3', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/orders/[token]/receipt/page.tsx': { page: 'D1', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/orders/new/page.tsx': { page: 'O2s', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/products/[id]/edit/page.tsx': { page: 'P2', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/products/new/page.tsx': { page: 'P2', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/public-profile/builder/page.tsx': { page: 'T1', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/settings/channels/[channelId]/ice-breakers/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/(fullscreen)/settings/channels/line/[channelId]/rich-menu/page.tsx': { page: 'H3', status: 'PENDING' },
  'src/app/(paces)/seller/auth/app-enter/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/app-oauth/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/callback/[provider]/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/layout.tsx': { class: 'PUBLIC', reason: 'shell หน้า auth ก่อนล็อกอิน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/new-pass/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/reset-pass/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/sign-in/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/sign-up/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/auth/verify-otp/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/choose-shop/page.tsx': { class: 'SELF', reason: 'เลือกร้านที่จะเข้า — อ่านร้านส่วนตัวของผู้ใช้เอง', status: 'DECLARED' },
  'src/app/(paces)/seller/i/[slug]/page.tsx': { class: 'SELF', reason: 'รับคำเชิญเข้าร้านโดยผู้ใช้ที่ล็อกอิน — ยังไม่เป็นสมาชิก', status: 'DECLARED' },
  'src/app/(paces)/seller/i/invalid/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/(paces)/seller/layout.tsx': { class: 'MEMBER', reason: 'shell ของ seller ทั้งโซน — session/provider ไม่ตัดสินสิทธิ์ (หน้าลูกประกาศ cap เอง)', status: 'DECLARED' },
  'src/app/(paces)/seller/onboarding/page.tsx': { class: 'SELF', reason: 'onboarding ของผู้ใช้เอง (ร้านส่วนตัว)', status: 'DECLARED' },
  'src/app/(paces)/seller/register/page.tsx': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/account/badge-progress/route.ts': { class: 'MEMBER', reason: 'ความสำเร็จ/ป้ายของร้าน — มติ C-1 ทุกสมาชิกเห็น (ไม่ใช่ capability)', status: 'DECLARED' },
  'src/app/api/account/categories/route.ts': { class: 'SELF', reason: 'onboarding/ผูกบัญชีของผู้ใช้เอง — ใช้ userId จาก session กับร้านส่วนตัว (PERSONAL) ไม่ผ่านสมาชิกร้านอื่น', status: 'DECLARED' },
  'src/app/api/account/check-username/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/delete/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/link/apple-native/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/link/reclaim/route.ts': { class: 'SELF', reason: 'onboarding/ผูกบัญชีของผู้ใช้เอง — ใช้ userId จาก session กับร้านส่วนตัว (PERSONAL) ไม่ผ่านสมาชิกร้านอื่น', status: 'DECLARED' },
  'src/app/api/account/link/remove/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/link/send-otp/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/link/start/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/notification-sound/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/notifications/route.ts': { class: 'SELF', reason: 'ค่าแจ้งเตือนของผู้ใช้เองต่อร้านที่เป็นสมาชิก (userId จาก session)', status: 'DECLARED' },
  'src/app/api/account/onboarding-checklist/route.ts': { class: 'SELF', reason: 'onboarding/ผูกบัญชีของผู้ใช้เอง — ใช้ userId จาก session กับร้านส่วนตัว (PERSONAL) ไม่ผ่านสมาชิกร้านอื่น', status: 'DECLARED' },
  'src/app/api/account/otp-for-password/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/sales-channels/route.ts': { class: 'SELF', reason: 'onboarding/ผูกบัญชีของผู้ใช้เอง — ใช้ userId จาก session กับร้านส่วนตัว (PERSONAL) ไม่ผ่านสมาชิกร้านอื่น', status: 'DECLARED' },
  'src/app/api/account/set-password-otp/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/set-password/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/set-phone/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/account/shop-info/route.ts': { class: 'SELF', reason: 'onboarding/ผูกบัญชีของผู้ใช้เอง — ใช้ userId จาก session กับร้านส่วนตัว (PERSONAL) ไม่ผ่านสมาชิกร้านอื่น', status: 'DECLARED' },
  'src/app/api/auctions/[id]/bid/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/auctions/[id]/buy-now/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/auctions/[id]/react/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/auctions/[id]/watch/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/auth/[...nextauth]/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/auth/cleanup/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/badges/[badgeId]/estimate/route.ts': { class: 'MEMBER', reason: 'ความสำเร็จ/ป้ายของร้าน — มติ C-1 ทุกสมาชิกเห็น (ไม่ใช่ capability)', status: 'DECLARED' },
  'src/app/api/badges/[badgeId]/rarity/route.ts': { class: 'MEMBER', reason: 'ความสำเร็จ/ป้ายของร้าน — มติ C-1 ทุกสมาชิกเห็น (ไม่ใช่ capability)', status: 'DECLARED' },
  'src/app/api/business/cancel/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/context/route.ts': { class: 'SELF', reason: 'สลับ/อ่านบริบทร้านของผู้ใช้เอง — ตรวจสมาชิกภาพในตัวเอง (switch-context re-verify ก่อนเปลี่ยน)', status: 'DECLARED' },
  'src/app/api/business/downgrade/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/reactivate/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/invites/[inviteId]/route.ts': { DELETE: 'T2', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/invites/route.ts': { POST: 'T2', GET: 'T2', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/members/[memberId]/route.ts': { PATCH: 'T2', DELETE: 'T2', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/onboarding/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/restore/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/route.ts': { DELETE: 'T4', status: 'PENDING' },
  'src/app/api/business/shops/[shopId]/transfer/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/shops/route.ts': { class: 'SELF', reason: 'สร้างร้านธุรกิจใหม่ของผู้ใช้เอง — โควตาแพ็กเกจตัดสินใน service', status: 'DECLARED' },
  'src/app/api/business/subscribe/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/business/switch-context/route.ts': { class: 'SELF', reason: 'สลับ/อ่านบริบทร้านของผู้ใช้เอง — ตรวจสมาชิกภาพในตัวเอง (switch-context re-verify ก่อนเปลี่ยน)', status: 'DECLARED' },
  'src/app/api/business/upgrade/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/channels/[id]/ice-breakers/route.ts': { GET: 'H3', PUT: 'H3', status: 'PENDING' },
  'src/app/api/channels/[id]/route.ts': { DELETE: 'H3', status: 'PENDING' },
  'src/app/api/channels/facebook/callback/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/channels/facebook/confirm/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/facebook/connect/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/channels/facebook/pages/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/channels/facebook/stickers/route.ts': { GET: 'H2', status: 'PENDING' },
  'src/app/api/channels/line/[channelId]/health/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/[channelId]/quota/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/[channelId]/route.ts': { PATCH: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/connect/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/rich-menu/activate/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/rich-menu/consent/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/rich-menu/deactivate/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/channels/line/rich-menu/route.ts': { GET: 'H3', PUT: 'H3', status: 'PENDING' },
  'src/app/api/channels/route.ts': { GET: 'H1', POST: 'H3', status: 'PENDING' },
  'src/app/api/chat/ai-quota/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/comments/[commentId]/private-reply/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/comments/[commentId]/reply/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/comments/[commentId]/resolve/route.ts': { POST: 'H2', DELETE: 'H2', status: 'PENDING' },
  'src/app/api/chat/comments/list/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/comments/posts/[postId]/comment/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/comments/posts/[postId]/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/comments/resolve-expired/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/ai-suggest/auto/route.ts': { POST: 'H2', GET: 'H1', PATCH: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/ai-suggest/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/auto-reply/route.ts': { PATCH: 'X2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/crm/route.ts': { GET: 'H1', PATCH: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/customer-prefill/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/follow-ups/route.ts': { GET: 'X2', POST: 'X2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/interested-products/[rowId]/route.ts': { DELETE: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/interested-products/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/library/route.ts': { GET: 'X2', POST: 'X2', DELETE: 'X2', PATCH: 'X2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/memory/refresh/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/memory/route.ts': { GET: 'H1', PUT: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/messages/[messageId]/route.ts': { DELETE: 'H2', POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/messages/route.ts': { GET: 'H1', POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/orders/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/preview/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/read/route.ts': { POST: 'H1', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/route.ts': { PATCH: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/thread-control/route.ts': { POST: 'X2', status: 'PENDING' },
  'src/app/api/chat/conversations/[id]/typing/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/chat/conversations/route.ts': { POST: 'H2', GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/giphy/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/chat/groups/[id]/route.ts': { PATCH: 'X2', DELETE: 'X2', status: 'PENDING' },
  'src/app/api/chat/groups/route.ts': { GET: 'X2', POST: 'X2', status: 'PENDING' },
  'src/app/api/chat/inbox-tab-counts/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/preferences/route.ts': { GET: 'X2', PATCH: 'X2', status: 'PENDING' },
  'src/app/api/chat/problem-count/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/quick-messages/[id]/route.ts': { PATCH: 'X2', DELETE: 'X2', status: 'PENDING' },
  'src/app/api/chat/quick-messages/route.ts': { GET: 'X2', POST: 'X2', PATCH: 'X2', status: 'PENDING' },
  'src/app/api/chat/shop-context/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/spam-unread/route.ts': { GET: 'H1', status: 'PENDING' },
  'src/app/api/chat/tags/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/chat/upload/route.ts': { POST: 'H2', status: 'PENDING' },
  'src/app/api/client-error/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/cron/chat-response-metrics/route.ts': { class: 'CRON', reason: 'cron ตรวจ CRON_SECRET ไม่มีผู้ใช้/บทบาท', status: 'DECLARED' },
  'src/app/api/expenses/[id]/route.ts': { PATCH: 'F2', DELETE: 'F2', status: 'PENDING' },
  'src/app/api/expenses/report/route.ts': { GET: 'F1', status: 'PENDING' },
  'src/app/api/expenses/route.ts': { GET: 'F1', POST: 'F2', status: 'PENDING' },
  'src/app/api/files/[...fileId]/route.ts': { class: 'MEMBER', reason: 'ไฟล์หลายชนิดในทางเดียว (KYC/สลิปเติมเงิน/สลิปออเดอร์/เอกสารแชท) — T2/T3 ต้องแตก cap ตามชนิดไฟล์ (F3/O5/H1) ก่อน DECLARED', status: 'PENDING' },
  'src/app/api/finance/receivables/route.ts': { GET: 'F1', status: 'PENDING' },
  'src/app/api/follow-ups/[id]/complete/route.ts': { POST: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/[id]/outcome/route.ts': { POST: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/[id]/reopen/route.ts': { POST: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/[id]/route.ts': { PATCH: 'X2', DELETE: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/[id]/snooze/route.ts': { POST: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/board/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/inbox-counts/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/follow-ups/mine/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/geo/reverse/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/i/[slug]/accept/route.ts': { class: 'SELF', reason: 'รับคำเชิญเข้าร้านของผู้ใช้ที่ล็อกอิน — ยังไม่เป็นสมาชิก (ตรวจ token คำเชิญใน service)', status: 'DECLARED' },
  'src/app/api/i/[slug]/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/iap/apple/verify/route.ts': { class: 'SELF', reason: 'ซื้อแพ็กเกจผ่าน Apple IAP ของผู้ใช้เอง (session userId)', status: 'DECLARED' },
  'src/app/api/inspector/rounds/[id]/complete/route.ts': { class: 'PLATFORM_ADMIN', reason: 'ผู้ตรวจของแพลตฟอร์ม (requireInspector) ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/inspector/rounds/[id]/results/route.ts': { class: 'PLATFORM_ADMIN', reason: 'ผู้ตรวจของแพลตฟอร์ม (requireInspector) ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/inspector/rounds/[id]/route.ts': { class: 'PLATFORM_ADMIN', reason: 'ผู้ตรวจของแพลตฟอร์ม (requireInspector) ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/inspector/rounds/route.ts': { class: 'PLATFORM_ADMIN', reason: 'ผู้ตรวจของแพลตฟอร์ม (requireInspector) ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/inventory/csv/export/route.ts': { GET: 'P2', status: 'PENDING' },
  'src/app/api/inventory/csv/import/route.ts': { POST: 'P2', status: 'PENDING' },
  'src/app/api/inventory/movements/route.ts': { GET: 'P2', status: 'PENDING' },
  'src/app/api/inventory/reactivate/route.ts': { POST: 'F4', status: 'PENDING' },
  'src/app/api/inventory/stock/adjust/route.ts': { POST: 'P2', status: 'PENDING' },
  'src/app/api/inventory/subscribe/route.ts': { POST: 'F4', status: 'PENDING' },
  'src/app/api/inventory/upgrade/route.ts': { POST: 'F4', status: 'PENDING' },
  'src/app/api/invites/[inviteId]/accept/route.ts': { class: 'SELF', reason: 'รับคำเชิญเข้าร้านของผู้ใช้ที่ล็อกอิน — ยังไม่เป็นสมาชิก', status: 'DECLARED' },
  'src/app/api/line-report/bind-code/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/ack/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/bind-code/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/route.ts': { GET: 'T4', PATCH: 'T4', DELETE: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/shops/route.ts': { PUT: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/template/route.ts': { PUT: 'T4', DELETE: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/[id]/test/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/line-report/groups/route.ts': { GET: 'T4', status: 'PENDING' },
  'src/app/api/line-report/product-image/route.ts': { GET: 'T4', status: 'PENDING' },
  'src/app/api/login/apple-native/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/login/apple-native/start/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/login/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/notifications/read/route.ts': { class: 'SELF', reason: 'แจ้งเตือนของผู้ใช้เอง (userId จาก session)', status: 'DECLARED' },
  'src/app/api/notifications/route.ts': { class: 'SELF', reason: 'แจ้งเตือนของผู้ใช้เอง (userId จาก session)', status: 'DECLARED' },
  'src/app/api/o/[token]/return-label/route.ts': { class: 'PUBLIC', reason: 'ผู้ซื้อเปิดใบปะหน้าขากลับด้วย publicToken ของออเดอร์ (กุญแจเดียวกับหน้า /o/[token])', status: 'DECLARED' },
  'src/app/api/o/sms/[code]/route.ts': { class: 'PUBLIC', reason: 'ลิงก์ SMS short-code ของผู้ซื้อ — consume แล้วตั้งคุกกี้ปลดล็อก', status: 'DECLARED' },
  'src/app/api/orders/[token]/access-url/route.ts': { POST: 'O7', status: 'PENDING' },
  'src/app/api/orders/[token]/appointment-summary/route.ts': { GET: 'O1', status: 'PENDING' },
  'src/app/api/orders/[token]/appointment/confirm/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/appointment/outcome/route.ts': { POST: 'O4', status: 'PENDING' },
  'src/app/api/orders/[token]/appointment/reschedule-request/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/appointment/route.ts': { PATCH: 'O3', status: 'PENDING' },
  'src/app/api/orders/[token]/auth-flow/start/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/auto-order/discard/route.ts': { POST: 'O2', status: 'PENDING' },
  'src/app/api/orders/[token]/auto-order/retry/route.ts': { POST: 'O2', status: 'PENDING' },
  'src/app/api/orders/[token]/buyer-reputation/route.ts': { GET: 'O1', status: 'PENDING' },
  'src/app/api/orders/[token]/cancel/route.ts': { POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/claim/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/cod-received/route.ts': { POST: 'O5', DELETE: 'O5', status: 'PENDING' },
  'src/app/api/orders/[token]/confirm/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/dispute/resolve/route.ts': { POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/dispute/route.ts': { POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/handover/route.ts': { POST: 'S1', DELETE: 'S1', status: 'PENDING' },
  'src/app/api/orders/[token]/link-account/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/payment-confirm/route.ts': { POST: 'O5', DELETE: 'O5', status: 'PENDING' },
  'src/app/api/orders/[token]/payments/[paymentId]/route.ts': { DELETE: 'O5', status: 'PENDING' },
  'src/app/api/orders/[token]/payments/route.ts': { POST: 'O5', GET: 'O5', status: 'PENDING' },
  'src/app/api/orders/[token]/receipt/route.ts': { POST: 'D1', status: 'PENDING' },
  'src/app/api/orders/[token]/return-quote/route.ts': { POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/returns/[returnId]/route.ts': { POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/returns/route.ts': { GET: 'O6', POST: 'O6', status: 'PENDING' },
  'src/app/api/orders/[token]/review/reply/route.ts': { POST: 'T1', DELETE: 'T1', status: 'PENDING' },
  'src/app/api/orders/[token]/review/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/route.ts': { GET: 'O1', PATCH: 'O3', status: 'PENDING' },
  'src/app/api/orders/[token]/send-sms/route.ts': { POST: 'O7', status: 'PENDING' },
  'src/app/api/orders/[token]/ship/route.ts': { POST: 'S1', PATCH: 'S1', status: 'PENDING' },
  'src/app/api/orders/[token]/shipment-evidence/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/orders/[token]/slip/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/[token]/verify-phone/route.ts': { class: 'BUYER', reason: 'ฝั่งผู้ซื้อ (session ผู้ซื้อ/เจ้าของออเดอร์) — ไม่ใช่สมาชิกร้าน', status: 'DECLARED' },
  'src/app/api/orders/customers/route.ts': { GET: 'C1', status: 'PENDING' },
  'src/app/api/orders/parse-address/route.ts': { POST: 'O2s', status: 'PENDING' },
  'src/app/api/orders/route.ts': { GET: 'O1', POST: 'O2s', status: 'PENDING' },
  'src/app/api/otp/send/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/otp/verify/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/products/[id]/like/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/products/[id]/route.ts': { PATCH: 'P2', DELETE: 'P2', status: 'PENDING' },
  'src/app/api/products/route.ts': { GET: 'P1', POST: 'P2', status: 'PENDING' },
  'src/app/api/public/profile/[username]/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/public/reviews/[username]/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/scam-reports/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/scam-reports/search/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/seller/app-ticket/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/seller/auctions/[id]/cancel/route.ts': { POST: 'X1', status: 'PENDING' },
  'src/app/api/seller/auctions/[id]/end-early/route.ts': { POST: 'X1', status: 'PENDING' },
  'src/app/api/seller/auctions/[id]/publish/route.ts': { POST: 'X1', status: 'PENDING' },
  'src/app/api/seller/auctions/[id]/route.ts': { GET: 'X1', PATCH: 'X1', status: 'PENDING' },
  'src/app/api/seller/auctions/route.ts': { POST: 'X1', GET: 'X1', status: 'PENDING' },
  'src/app/api/seller/auto-order/channels/route.ts': { PUT: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/dry-run/route.ts': { POST: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/health/route.ts': { POST: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/phrases/route.ts': { PUT: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/route.ts': { GET: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/status/route.ts': { PATCH: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/test-threads/[conversationId]/route.ts': { DELETE: 'X3', status: 'PENDING' },
  'src/app/api/seller/auto-order/test-threads/route.ts': { GET: 'X3', POST: 'X3', status: 'PENDING' },
  'src/app/api/seller/customers/[key]/contact/route.ts': { GET: 'C1', status: 'PENDING' },
  'src/app/api/seller/inspection/cancel/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/seller/inspection/documents/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/seller/inspection/route.ts': { GET: 'T4', status: 'PENDING' },
  'src/app/api/seller/inspection/subscribe/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/seller/inspection/upgrade/route.ts': { POST: 'T4', status: 'PENDING' },
  'src/app/api/seller/iship/boxes/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/connection/route.ts': { GET: 'S1', POST: 'S2', DELETE: 'S2', status: 'PENDING' },
  'src/app/api/seller/iship/connection/verify/route.ts': { POST: 'S2', status: 'PENDING' },
  'src/app/api/seller/iship/couriers/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/labels/bulk/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/order-context/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/pickups/[id]/cancel/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/pickups/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/price/compare/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/price/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/settings/route.ts': { GET: 'S1', PUT: 'S2', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/[id]/cancel/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/[id]/label/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/[id]/retry/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/[id]/traces/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/[id]/unlink/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/link/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/shipments/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/unlinked/import/route.ts': { POST: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/unlinked/preview/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/iship/unlinked/route.ts': { GET: 'S1', status: 'PENDING' },
  'src/app/api/seller/pin-slots/buy/route.ts': { POST: 'F4', status: 'PENDING' },
  'src/app/api/seller/portfolio-series/route.ts': { GET: 'F1', status: 'PENDING' },
  'src/app/api/seller/products/[id]/pin/route.ts': { POST: 'P2', status: 'PENDING' },
  'src/app/api/seller/products/[id]/unpin/route.ts': { POST: 'P2', status: 'PENDING' },
  'src/app/api/seller/push-token/route.ts': { class: 'SELF', reason: 'push token ของอุปกรณ์ผู้ใช้เอง (requireAppUser)', status: 'DECLARED' },
  'src/app/api/seller/reports/agents/[agentId]/conversations/route.ts': { GET: 'X4', status: 'PENDING' },
  'src/app/api/seller/reports/agents/[agentId]/route.ts': { GET: 'X4', status: 'PENDING' },
  'src/app/api/seller/reports/agents/route.ts': { GET: 'X4', status: 'PENDING' },
  'src/app/api/seller/sales-series/route.ts': { GET: 'F1', status: 'PENDING' },
  'src/app/api/shops/[id]/route.ts': { PATCH: 'T1', status: 'PENDING' },
  'src/app/api/shops/ai-settings/route.ts': { GET: 'H3', PUT: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/ads/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/chatbot/guardrails/[guardrailId]/route.ts': { PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/chatbot/guardrails/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/chatbot/route.ts': { GET: 'H3', PATCH: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/chatbot/test-threads/[conversationId]/route.ts': { DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/chatbot/test-threads/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/config/route.ts': { GET: 'H3', PATCH: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/duplicate/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/guardrails/[guardrailId]/route.ts': { PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/guardrails/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/phrases/[phraseId]/route.ts': { DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/phrases/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/route.ts': { GET: 'H3', PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/test-threads/[conversationId]/route.ts': { DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/[id]/test-threads/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/keywords/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/knowledge/[qnaId]/route.ts': { PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/knowledge/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/logs/[id]/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/logs/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/rules/[id]/route.ts': { PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/rules/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/auto-reply/simulate/route.ts': { POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/check-slug/route.ts': { class: 'PUBLIC', reason: 'เช็คว่า slug ว่างไหม (ไม่ผูกผู้ใช้/ร้าน คืนแค่ available) — ไม่ใช่ข้อมูลร้านเฉพาะราย', status: 'DECLARED' },
  'src/app/api/shops/comment-reply/config/route.ts': { PATCH: 'H3', status: 'PENDING' },
  'src/app/api/shops/comment-reply/logs/route.ts': { GET: 'H3', status: 'PENDING' },
  'src/app/api/shops/comment-reply/rules/[ruleId]/route.ts': { PATCH: 'H3', DELETE: 'H3', status: 'PENDING' },
  'src/app/api/shops/comment-reply/rules/route.ts': { GET: 'H3', POST: 'H3', status: 'PENDING' },
  'src/app/api/shops/current/appointment-settings/route.ts': { PATCH: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/appointments/day/route.ts': { GET: 'Q1', status: 'PENDING' },
  'src/app/api/shops/current/appointments/route.ts': { GET: 'Q1', status: 'PENDING' },
  'src/app/api/shops/current/bookings/[token]/confirm/route.ts': { POST: 'O4', status: 'PENDING' },
  'src/app/api/shops/current/bookings/[token]/housekeeping/route.ts': { PATCH: ['Q1', 'O4'], status: 'PENDING' },
  'src/app/api/shops/current/bookings/[token]/route.ts': { PATCH: 'O3', status: 'PENDING' },
  'src/app/api/shops/current/bookings/quote/route.ts': { POST: 'O2', status: 'PENDING' },
  'src/app/api/shops/current/bookings/route.ts': { POST: 'O2', status: 'PENDING' },
  'src/app/api/shops/current/customers/lookup/route.ts': { GET: 'C1', status: 'PENDING' },
  'src/app/api/shops/current/housekeepers/[id]/route.ts': { PATCH: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/housekeepers/route.ts': { GET: 'Q1', POST: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/invite-links/[slug]/route.ts': { DELETE: 'T2', status: 'PENDING' },
  'src/app/api/shops/current/invite-links/route.ts': { POST: 'T2', GET: 'T2', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/facebook-posts/mirror/route.ts': { POST: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/item-visibility/route.ts': { PATCH: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/library/route.ts': { GET: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/prices/route.ts': { PATCH: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/publish/route.ts': { PATCH: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/page-builder/route.ts': { PUT: 'T1', status: 'PENDING' },
  'src/app/api/shops/current/rooms/[roomId]/route.ts': { GET: 'Q1', PATCH: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/rooms/availability/route.ts': { GET: 'Q1', status: 'PENDING' },
  'src/app/api/shops/current/rooms/route.ts': { GET: 'Q1', POST: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/service-resources/[resourceId]/route.ts': { PATCH: 'Q2', DELETE: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/service-resources/availability/route.ts': { GET: 'Q1', status: 'PENDING' },
  'src/app/api/shops/current/service-resources/route.ts': { GET: 'Q1', POST: 'Q2', status: 'PENDING' },
  'src/app/api/shops/current/shortcuts/[slug]/pin/route.ts': { class: 'MEMBER', reason: 'ทางลัดเมนูที่ปักหมุด = display ไม่ใช่ capability', status: 'DECLARED' },
  'src/app/api/shops/current/shortcuts/[slug]/unpin/route.ts': { class: 'MEMBER', reason: 'ทางลัดเมนูที่ปักหมุด = display ไม่ใช่ capability', status: 'DECLARED' },
  'src/app/api/shops/current/shortcuts/reset/route.ts': { class: 'MEMBER', reason: 'ทางลัดเมนูที่ปักหมุด = display ไม่ใช่ capability', status: 'DECLARED' },
  'src/app/api/shops/current/shortcuts/route.ts': { class: 'MEMBER', reason: 'ทางลัดเมนูที่ปักหมุด = display ไม่ใช่ capability (FR-RP-09: ซ่อนเมื่อไม่มีสิทธิ์ใน T6)', status: 'DECLARED' },
  'src/app/api/shops/current/videos/route.ts': { GET: 'T1', PUT: 'T1', status: 'PENDING' },
  'src/app/api/shops/open-personal/route.ts': { class: 'SELF', reason: 'เปิดร้านส่วนตัวของผู้ใช้เอง', status: 'DECLARED' },
  'src/app/api/shops/payout/route.ts': { PATCH: 'T3', status: 'PENDING' },
  'src/app/api/shops/receipt-profile/route.ts': { PATCH: 'X5', status: 'PENDING' },
  'src/app/api/shops/route.ts': { class: 'SELF', reason: 'อ่าน/สร้างร้านส่วนตัวของผู้ใช้เอง (getShopByUserId = PERSONAL)', status: 'DECLARED' },
  'src/app/api/shops/slug/route.ts': { POST: 'T1', status: 'PENDING' },
  'src/app/api/shops/update/route.ts': { class: 'SELF', reason: 'ปรับโปรไฟล์ร้านส่วนตัว (PERSONAL) ของผู้ใช้เองใน flow onboarding', status: 'DECLARED' },
  'src/app/api/tags/route.ts': { GET: 'X2', status: 'PENDING' },
  'src/app/api/upload/route.ts': { class: 'MEMBER', reason: 'legacy upload (ไม่มีใครเรียกแล้ว) รับไฟล์ทุก purpose — T2/T3 ต้องปิดหรือแตก cap ตาม purpose ก่อน DECLARED', status: 'PENDING' },
  'src/app/api/uploads/commit/route.ts': { class: 'MEMBER', reason: 'อัปโหลดหลาย purpose (แชท/รูป/เอกสาร) — T2/T3 ต้องแตก cap ตาม purpose (CHAT→H2, IMAGE→P2/T1) ก่อน DECLARED', status: 'PENDING' },
  'src/app/api/uploads/local/[...path]/route.ts': { class: 'PUBLIC', reason: 'PUT ไปยัง storage ท้องถิ่นของ dev (ticket ลงนามใน URL) — ไม่มีใน prod', status: 'DECLARED' },
  'src/app/api/uploads/ticket/route.ts': { class: 'MEMBER', reason: 'อัปโหลดหลาย purpose (แชท/รูป/เอกสาร) — T2/T3 ต้องแตก cap ตาม purpose (CHAT→H2, IMAGE→P2/T1) ก่อน DECLARED', status: 'PENDING' },
  'src/app/api/users/check-phone/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/users/check-username/route.ts': { class: 'PUBLIC', reason: 'สาธารณะ/ก่อนล็อกอิน — ไม่ผูกผู้ใช้หรือร้าน', status: 'DECLARED' },
  'src/app/api/users/me/route.ts': { class: 'SELF', reason: 'ข้อมูลของผู้ใช้เองจาก session (userId) — ไม่ผูกร้าน/บทบาท', status: 'DECLARED' },
  'src/app/api/verification/route.ts': { GET: 'T1', POST: 'T1', status: 'PENDING' },
  'src/app/api/wallet/events/route.ts': { GET: 'F3', POST: 'F3', status: 'PENDING' },
  'src/app/api/wallet/route.ts': { GET: 'F3', status: 'PENDING' },
  'src/app/api/wallet/topup/route.ts': { POST: 'F3', status: 'PENDING' },
}
